- hosts: dcloud_switches
  connection: local
  roles:
    - { role: nxos_common }

- hosts: nxos_leaf
  connection: local
  roles:
    - { role: nxos_leaf }

- hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/webex_teams_main.yml
  roles:
    - {role: webex_teams_message}